name              "dart-install"
maintainer        "dart"
maintainer_email  "mariotti.enrico@gmail.com"
license           ""
description       ""
long_description  ""
version           "0.0.1"
recipe            "dart-install", ""