name              "dart-cookbook"
maintainer        "dart"
maintainer_email  "mariotti.enrico@gmail.com"
license           ""
description       ""
long_description  ""
version           "1.0.0"
recipe            "dart-cookbook", ""